variable "project_name" {
  description = "Project name for resource naming (backward compatibility)"
  type        = string
  default     = "base-env"
}

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-west-2"
}

variable "base_project_name" {
  description = "Name of the base project to reference existing resources"
  type        = string
  default     = "base-env"
}

variable "tfe_project_name" {
  description = "Name of the TFE project for resource naming"
  type        = string
  default     = "tfe"
}

variable "tfe_instance_type" {
  description = "EC2 instance type for Terraform Enterprise instance"
  type        = string
  default     = "t3.large"
}

variable "key_pair_name" {
  description = "Name of the AWS key pair to use for TFE instance"
  type        = string
}

variable "allowed_cidr_blocks" {
  description = "CIDR blocks allowed to access TFE (in addition to bastion)"
  type        = list(string)
  default     = []
}

variable "tfe_hostname" {
  description = "Hostname for TFE installation"
  type        = string
  default     = "terraform-enterprise.local"
}

variable "generate_new_key" {
  description = "Whether a new key was generated by the base infrastructure"
  type        = bool
  default     = false
}
